language: node_js
node_js:
  - "5.2.0"

before_script:
  - npm install -g gulp
script: gulp jest

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
env:
  CXX=g++-4.8